menu:
- {name: 'Publications', url: '/publications'}
- {name: 'Courses', url: '/courses'}
- {name: 'CV', url: '/cv'}
- {name: 'Contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/pawansnegi'}
- {icon: 'twitter', link: 'https://twitter.com/pawan_s_negi'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/pawan-negi-49bba546'}

contacts:
- {name: 'Pawan Negi', title: 'Senior Research Associate', department:
'Applied Mathematics', institution: 'Illinois Institute of Technology',
institution_address: '10 W 32 St, Chicago, 60616', phone: '--', email: 'Pawan2713@gmail.com', office:
'RE213', image: 'assets/img/contact.jpg'}
